### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by thefiredragon** [Lorys89/Dell_Vostro_5401-ICE-LAKE#1]
Did you got full brightness working?

**Comment by Lorys89** [comment]
> Did you got full brightness working?

if he uses the kext AppleBacklightSmoother, the brightness always works but the maximum value is lower than the real one, which I get by not using the kext, but occurs when he does not use the kext that the pc starts up without screen backlight and after 3 minutes of blow activates and works

**Comment by Lorys89** [comment]
> Did you got full brightness working?

create the repo with your efi, as I did my repo, on github there are no efi ice lakes, so as to help the next ice lake users 💪

**Comment by thefiredragon** [comment]
I'll do it :) this should not be a Problem.
Only I hope well have some years till apple will stop Support Intel based machines. I'm not a ARM CPU friend

**Comment by Lorys89** [comment]
> I'll do it :) this should not be a Problem.
> Only I hope well have some years till apple will stop Support Intel based machines. I'm not a ARM CPU friend

for another 6 years at least, there will be support for intel CPU
