### ISSUE TITLE
Dell Vostro 5501 with Qualcomm Atheros WiFi

### ISSUE THREAD

**Issue by cboukouv** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#2]
First, thank you for this great project, I managed to install easily 11.2.3 as if it was on a Mac. However, my laptop unfortunately has a Qualcomm Atheros QCA6174 802.11ac wifi card (pci186c,3e). Are you aware of any way to support this card on MacOS with Opencore?

Alternatively, is there any USB WiFi card that you recommend that works with Big Sur? Or any Broadcom based and supported on Big Sur that is relatively cheap?

Thank you

**Comment by Lorys89** [comment]
dw1830, dw1560, dw1820a, bcm94360ng all works

**Comment by Lorys89** [comment]
close as resolved, and thank you for the compliments

**Comment by Lorys89** [comment]
for more help visit the support chat for ice lake generation
https://gitter.im/ICE-LAKE-HACKINTOSH-DEVELOPMENT/community
