### ISSUE TITLE
No GPU Acceleration of Vostro 5501

### ISSUE THREAD

**Issue by cboukouv** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#3]
The last version released boots without GPU Acceleration. When I replace the EFI folder with the previous one, GPU Acceleration is back.

**Comment by Lorys89** [comment]
for i5 and i3 g1 cpu holders in the igpu patch you must inject device id 528A0000

**Comment by Lorys89** [comment]
![IMG_20210510_103430_548](https://user-images.githubusercontent.com/64613690/117630344-65168300-b17b-11eb-8120-cc3a39b000e8.jpg)
use this patch last, if you see the addition and device id that in your case is not native, update efi in the repository so can use it who has cpu i3 G1 and i5 G1
