### ISSUE TITLE
About -disablegfxpreemption

### ISSUE THREAD

**Issue by Mateo1234454545** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#4]
Can you explain what the -disablegfxpreemption boot arg does?
I don't find it in weg docs.
Thanks.

**Comment by Lorys89** [comment]
> Can you explain what the -disablegfxpreemption boot arg does?
> I don't find it in weg docs.
> Thanks.

either you use that bootarg or you use the kext restrictevent, they serve to start recovery or in case of update macos you do not have kp

**Comment by Lorys89** [comment]
Boot args in AppleIntelICLGraphics
-noig (External display can only have maximum resolution 2560x1600，built-in display black screen)
-allow3d
-disablegfxpreemption
-disablegfxfirmware

**Comment by Lorys89** [comment]
Boot args in AppleIntelICLLPGraphicsFramebuffer
auxDelay (default is 100)
-10bpc
ig
-nodisplaysleepDC6
-noDC9
-linp0
dither=[0/1]
-yTileDisable (panic with an empty log)
-nocam
-disable3d
dc6config=[0/1/2/3/5]
-forceDSC
forceRenderStandby=[0/1] (default is 0)
-disablegfxfirmware
-nossc
EnableLPVPonExternal=[0/1] (default is 0)
-disableDynamicCDClk
-noasfu
GPU420Support=[0/1] (default is 0)
EnableGPUSubSamplingForHDR=[0/1] (default is 0)
enablefp16=[0/1] (default is 0)
-2dsim (2D GPU simulation)
-DisableIOFB
-panic_on_unload
-noCustomAux
meibootarg=[0/1] (default is 0)
tcncontrol (default is 0)
-nopsr
-nopsrexit
-novrr
-nodpb
-sfu
-forcepsr
dpbmode

**Comment by Mateo1234454545** [comment]
Thank you.

**Comment by Lorys89** [comment]
> Thank you.

do you own this laptop? why did I take this question for granted that ice lake users knew it!

**Comment by Mateo1234454545** [comment]
No, but I'm thinking of buying it.

**Comment by Lorys89** [comment]
I recommend you an xps 9300 that has the thunderbolt, the 5401 or 5501 has no thunderbolt
