### ISSUE TITLE
Having kernel panics on Dell Xps 7390 2in1 i7 1065G7

### ISSUE THREAD

**Issue by amaini** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#5]
Thanks for the EFI first of all.
Not sure what I am doing wrong but with your EFI I am able to load almost the whole bootloader but still getting the following error in photo. It Does dims the display before panic if that gives you any hint. My video memory in bios shows 160MB i did changed the DVMT as per your instructions to increase the video memory.
![IMG_2107](https://user-images.githubusercontent.com/32779161/141854266-dfd0b84e-c531-454b-8f12-8ead67bcfb42.JPG)

**Comment by Lorys89** [comment]
go to gitter ice lake, link is in my repo
