### ISSUE TITLE
cfg lock and DVMT

### ISSUE THREAD

**Issue by cansozbir** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#6]
Hello,
First of all, thank you for sharing this repo. This is the only repo I could find about my laptop. I have an Inspiron 5401 i5. 

I have never ever used or installed a Hackintosh, so I am totally newbie. What I want to ask is;

- You are warning us about bricking the device on "cfg lock and DVMT" step. Is this a necessary step for installation or is it just something about being able to use USB ports etc. It is really okay for me to not use them actually.
- Currently, my device is on bios version 1.7.2, can I still follow your instructions?
- I have read that G1 CPUs are not supported for Hackintosh, how is this repo compatible with my laptop? Can you explain me? Did you test it with an i5 or i3 instead of an i7?

Thanks a lot.

**Comment by Lorys89** [comment]
tested on i5 and i3 g1, it is compatible I warn that if you get the procedure wrong you can risk the brick, you can use the efi, the only difference between vostro series and inspiron is the lan port only in vostro series.
