### ISSUE TITLE
Brighyness at 50 % imposible to fix

### ISSUE THREAD

**Issue by PCAZILA** [Lorys89/DELL_VOSTRO_5401-ICE-LAKE#8]
Hello!!

Good I am in macOS Sonoma 14.3.2 with the latest EFI that you have uploaded but I have a problem, the first I can not adjust the brightness and is at MAX set.do not work the buttons attached photo of the event and video.

And second I have no way to make the screen back if I leave it for a while and goes to sleep.

Do you know if I have to touch something?, with another efi of an active fork I can adjust the brightness with not problem but i notice more graphics performance in yours.

I have the 1.4.4 bios and with modified cfg and video dvtl settings.

Thank you very much![image](https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE/assets/116582439/b378616a-c0ab-4fff-8924-590d520ab13d)![image](https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE/assets/116582439/587a4bf1-e987-452e-b4fd-d29ee1e19400)

**Comment by Lorys89** [comment]
Add bootarg:
-wegnoegpu
And reboot

**Comment by PCAZILA** [comment]
> Add bootarg:
> 
> -wegnoegpu
> 
> And reboot

Thanks mate!!!

That work perfectly also solve the sleep don't back.

So now is fully working

Regard's
